# Generated by Django 5.2.8 on 2025-12-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0002_taskresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(max_length=100)),
                ('correct_move', models.CharField(max_length=10)),
                ('level', models.CharField(default='easy', max_length=20)),
            ],
        ),
    ]
