# Generated by Django 5.2.8 on 2026-01-04 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0005_module_studentmodule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentmodule',
            unique_together={('student', 'module')},
        ),
        migrations.AddField(
            model_name='studentmodule',
            name='is_unlocked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentmodule',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='studentmodule',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='studentmodule',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='studentmodule',
            name='score',
        ),
    ]
