# Generated by Django 5.2.8 on 2026-01-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0006_alter_studentmodule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodule',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentmodule',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
